---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by quanchangnai.
--- DateTime: 2019/9/4 16:14
---
local Buffer = require("quan.message.Buffer")

local Message = {}

function Message.encode(msg, buffer)
    if buffer then
        buffer:reset()
    else
        buffer = Buffer.new()
    end

    buffer:writeInt(msg.id);
    buffer:writeLong(msg.seq);

    return buffer
end

function Message.decode(buffer, msg)
    if buffer.reading then
        buffer:reset()
    end

    local msgId = buffer:readInt();
    if msgId ~= msg.id then
        error(string.format("消息ID不匹配,期望值[%s],实际值[%s]", msg.id, msgId), 2)
    end
    msg.seq = buffer:readLong()

    return msg
end

return Message
