---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by quanchangnai.
--- DateTime: 2019/9/4 16:14
---

local Buffer = require("quan.message.Buffer")

local Message = {}

function Message.encode(msg, buffer)
    if buffer then
        buffer:reset()
    else
        buffer = Buffer.new()
    end

    buffer:writeInt(msg.id);

    return buffer
end

function Message.decode(buffer, msg)
    if buffer.reading then
        buffer:reset()
    end

    local msgId = buffer:readInt();
    if msgId ~= msg.id then
        error(string.format("消息ID不匹配,期望值[%s],实际值[%s]", msg.id, msgId), 2)
    end

    return msg
end

function Message.listToString(list)
    if not list then
        return "nil"
    end

    local result = "["
    local start = true
    for i, v in ipairs(list) do
        if not start then
            result = result .. ", ";
        end
        result = result .. tostring(v)
        start = false
    end
    result = result .. "]";

    return result;
end

function Message.setToString(set)
    return Message.listToString(set)
end

function Message.mapToString(map)
    if not map then
        return "nil"
    end

    local result = "{"
    local start = true
    for k, v in pairs(map) do
        if not start then
            result = result .. ", ";
        end
        result = result .. tostring(k) .. "=" .. tostring(v)
        start = false
    end
    result = result .. "}";

    return result;
end

return Message
