---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by quanchangnai.
--- DateTime: 2019/9/7 11:23
---

function table.size(t)
    assert(type(t) == "table", "参数[t]类型错误")
    local size = 0
    for k, v in pairs(t) do
        size = size + 1
    end
    return size
end

---
---构造只读表
---@param origin table 原始表
---@return table 只读表
-----
function table.readOnly(origin)
    assert(type(origin) == "table", "参数[origin]类型错误")
    local meta = {
        __index = origin,
        __newindex = function(table, key, value)
            error("不能修改只读表")
        end,
        __call = function(...)
            return origin(...)
        end
    }
    return setmetatable({}, meta)
end

local empty = table.readOnly({})

function table.empty()
    return empty
end

function table.toString(t)
    if not t then
        return "nil"
    end

    local result = "{"
    local start = true
    for k, v in pairs(t) do
        if not start then
            result = result .. ", ";
        end
        result = result .. tostring(k) .. "=" .. tostring(v)
        start = false
    end
    result = result .. "}";

    return result;
end

