---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by quanchangnai.
--- DateTime: 2019/9/4 14:34
---

local t1 = { aaa = 1, bbb = 2 }
local t2 = { ccc = 3, ddd = 4 }
setmetatable(t2, { __index = t1 })

t1.ccc = 444
t1.eee = 555

print("t1========")
for k, v in pairs(t1) do
    print(k .. "=" .. v)
end

print("t2.aaa", t2.aaa)
print("t2========")
for k, v in pairs(t2) do
    print(k .. "=" .. v)
end

local t = { aaa = 1 }

t = setmetatable(t, { __tostring = function()
    return "t.tostring"
end })

local function iter (list, i)
    i = i + 1
    local v = list[i]
    if v then
        return i, v
    end
end

local function iterate (list)
    return iter, list, 0
end

local list = { "a", "b", "c" }

print("iterate=======")
for i, v in iterate(list) do
    print(i, v)
end

local function lists (list)
    local i = 0
    return function()
        i = i + 1
        local v = list[i]
        if v then
            return i, v
        end
    end
end

print("lists=======")
for i, v in lists(list) do
    print(i, v)
end

local map = { a = "aaa", b = "bbb", c = "ccc" }

local function maps (map)
    local k = nil
    return function()
        k, v = next(map, k)
        if v then
            return k, v
        end
    end
end

print("maps=======")
for k, v in maps(map) do
    print(k, v)
end

print("date time=======")
local date=os.date("*t",16200)
for k, v in pairs(date) do
    print("k:",k,"v:",v)
end
