---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by quanchangnai.
--- DateTime: 2019/8/30 21:31
---
local Config = require("Config")

local BuffConfig = { _name = "BuffConfig" }
local prototype = {}

BuffConfig.__index = BuffConfig
prototype.__index = prototype

setmetatable(BuffConfig, Config)
setmetatable(prototype, BuffConfig)

function BuffConfig.new()
    local base = Config.new()
    local instance = {}
    setmetatable(instance, { __index = function(self, key)
        return prototype[key] or base[key]
    end })
    return instance
end

function prototype:test3()
    print("实例方法test3()")
end

return BuffConfig