---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by quanchangnai.
--- DateTime: 2019/9/4 15:16
---

local Buffer = require("Buffer")

local RoleInfo = {}

function RoleInfo.new()
    local instance = {
    }
    setmetatable(instance, { __index = RoleInfo })
    return instance
end

function RoleInfo:encode(buffer)

end

function RoleInfo.decode(buffer)

end

return RoleInfo