---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by quanchangnai.
--- DateTime: 2019/9/4 15:16
---

local Buffer = require("Buffer")

local UserInfo = {}

function UserInfo.new()
    local instance = {
    }
    setmetatable(instance, { __index = UserInfo })
    return instance
end

function UserInfo:encode(buffer)

end

function UserInfo.decode(buffer)

end

return UserInfo