---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by quanchangnai.
--- DateTime: 2021/8/5 17:23
---

---@module bits 原生位运算包装和扩展，实现了有符号右移位
local bits = {}

---按位非
function bits.bnot(v)
    return ~v
end

---按位与
function bits.band(a, b)
    return a & b
end

---按位或
function bits.bor(a, b)
    return a | b
end

---按位异或
function bits.bxor(a, b)
    return a ~ b
end

---左移位
function bits.lshift (a, b)
    return a << b
end

---无符号右移位
function bits.rshift(a, b)
    return a >> b
end

---有符号右移位
function bits.arshift(a, b)
    if a > 0 or b <= 0 then
        return a >> b
    else
        return (a >> b) | ~(-1 >> b)
    end
end

return bits