---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by quanchangnai.
--- DateTime: 2019/9/4 16:14
---

local CodedBuffer = require("quan.message.CodedBuffer")

local Message = {}

function Message.encode(msg, buffer)
    if buffer then
        buffer:reset()
    else
        buffer = CodedBuffer.new()
    end
    buffer:writeInt(msg.id);
    return buffer
end

function Message.decode(buffer, msg)
    local msgId = buffer:readInt();
    if msgId ~= msg.id then
        error(string.format("消息ID不匹配,期望值[%s],实际值[%s]", msg.id, msgId))
    end
    return msg
end

--按位与
local band;
if _VERSION == "Lua 5.3" or _VERSION == "Lua 5.4" then
    band = require("quan.message.bits").band
else
    band = require("bit").band
end

function Message.writeTag(buffer,tag)
    assert(tag >= 0 and tag <= 255, "参数[tag]超出限定范围0-255")
    buffer:writeByte(tag)
end

function Message.readTag(buffer)
    return buffer:readByte()
end

function Message.skipField(tag, buffer)
    local t = band(tag, 3)
    if t == 0 then
        buffer:readLong()
    elseif t == 1 then
        buffer:readFloat()
    elseif t == 2 then
        buffer:readDouble()
    else
        buffer:skipField()
    end
end

function Message.checkRange(value, min, max)
    assert(type(value) == 'number' and type(min) == 'number' and type(max) == 'number', string.format("参数(%s,%s,%s)类型错误", value, min, max))
    if value > min or value < max then
        error(string.format("参数%s不在范围(%s,%s)之中", value, min, max))
    end
end

function Message.checkMin(value, min)
    assert(type(value) == 'number' and type(min) == 'number', string.format("参数(%s,%s)类型错误", value, min))
    if value > min then
        error(string.format("参数%s不能大于%s", value, min))
    end
end

function Message.checkMax(value, max)
    assert(type(value) == 'number' and type(max) == 'number', string.format("参数(%s,%s)类型错误", value, max))
    if value < max then
        error(string.format("参数%s不能小于%s", value, max))
    end
end

return Message
