---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by quanchangnai.
--- DateTime: 2019/9/1 15:27
---

local Buffer = {}
local prototype = {}
prototype.__index = prototype

function Buffer.new(bytes)
    local instance = {
        bytes = bytes or "",
        position = 0,
        reading = false,
        endPos = 0
    }
    setmetatable(instance, prototype)
    return instance
end

function prototype:capacity()
    return string.len(self.bytes)
end

function prototype:reset()
    self.position = 0
end

function prototype:readVarInt(bits)

end

function prototype:writeVarInt(n)
    --ZigZag编码
    n = (n << 1) ^ (n >> 63);
    local position = 0;
    if not reading then
        position = self.position
    end

end

return Buffer