---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by quanchangnai.
--- DateTime: 2019/9/4 16:14
---
local Buffer = require("Buffer")

local Message = {}

function Message.instance(instance, class)
    local meta = {
        __index = class,
        __newindex = function()
            error("该操作不支持")
        end
    }
    setmetatable(instance, meta)
end

function Message.encode(msg, buffer)
    if buffer then
        buffer:reset()
    else
        buffer = Buffer.new()
    end

    buffer:writeInt(msg.getId());
    buffer:writeLong(msg.seq);

    return buffer
end

function Message.decode(msg, buffer)
    if buffer.reading then
        buffer:reset()
    end
    local msgId = buffer:readInt();
    if msgId ~= msg.getId() then
        error(string.format("消息ID不匹配,期望值[%s],实际值[%s]", msg.getId(), msgId))
    end
    msg.seq = buffer:readLong()
end

function mapSize(map)
    assert(type(map) == "table", "参数[map]类型错误")
    local size = 0
    for k, v in pairs(map) do
        size = size + 1
    end
    return size
end

return Message