---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by quanchangnai.
--- DateTime: 2019/8/30 17:36
---

local Buffer = require("Buffer")
local Message = require("Message")
local SRoleLogin = require("role.SRoleLogin")

print("MessageTest===========")
print()

function test1()
    print("test1===========")
    local str = ""
    for i = 1, 3 do
        str = str .. string.char(i)
    end
    print(str[2])
    print("str=" .. string.len(str))
    print(string.unpack("bbb", str))
    print(str:byte(1, string.len(str)))

    str = string.pack("bbb", 23, 43, 54)
    print(string.unpack("bbb", str))
end

function testBuffer()
    print("testBuffer===========")
    local buffer = Buffer.new()
    buffer:writeBool(true)
    buffer:writeInt(70)
    buffer:writeInt(2423)
    buffer:writeFloat(13.43)
    buffer:writeDouble(4242.432)
    buffer:writeFloat(132.32434, 2)
    buffer:writeDouble(342254.653254, 2)
    buffer:writeString("搭顺风车")

    print("buffer:size()=" .. buffer:size())

    print(buffer:readBool())
    print(buffer:readInt())
    buffer:reset()
    print(buffer:readBool())
    print(buffer:readInt())
    print(buffer:readInt())
    print(buffer:readFloat())
    print(buffer:readDouble())
    print(buffer:readFloat(2))
    print(buffer:readDouble(2))
    print(buffer:readString())

    local file = io.open("E:\\buffer", "w")
    file:write(buffer.bytes)
    file:flush()

    buffer:reset()
    buffer:writeInt(45)
    buffer:writeString("奋斗服务")
    print(buffer:readInt())
    buffer = Buffer.new(buffer:remainingBytes())
    print(buffer:readString())

    print(table.unpack({ 12, 45, 33 }))
end

function testMessage()
    local sRoleLogin1 = SRoleLogin.new()
    sRoleLogin1.roleId = 123
    sRoleLogin1.roleName = "abc"
    local buffer = sRoleLogin1:encode()

    local sRoleLogin2 = SRoleLogin.new()
    sRoleLogin2:decode(buffer)
    print("sRoleLogin2.roleId=" .. sRoleLogin2.roleId .. ",sRoleLogin2.roleName=" .. sRoleLogin2.roleName)

end

--test1()
--print()
--testBuffer()
testMessage()
